### ISSUE TITLE
isnt working

### ISSUE THREAD

**Issue by 256bytecode** [RecruitMk/PSTroll#1]
[11:32:48.389272] (error)	SPECTATOR.lua: D:\Grand Theft Auto SA\moonloader\SPECTATOR.lua:49: module 'samp.events' not found:
	no field package.preload['samp.events']
	no file 'D:\Grand Theft Auto SA\moonloader\lib\samp\events.lua'
	no file 'D:\Grand Theft Auto SA\moonloader\lib\samp\events\init.lua'
	no file 'D:\Grand Theft Auto SA\moonloader\samp\events.lua'
	no file 'D:\Grand Theft Auto SA\moonloader\samp\events\init.lua'
	no file '.\samp\events.lua'
	no file 'D:\Grand Theft Auto SA\moonloader\lib\samp\events.luac'
	no file 'D:\Grand Theft Auto SA\moonloader\lib\samp\events\init.luac'
	no file 'D:\Grand Theft Auto SA\moonloader\samp\events.luac'
	no file 'D:\Grand Theft Auto SA\moonloader\samp\events\init.luac'
	no file '.\samp\events.luac'
	no file 'D:\Grand Theft Auto SA\moonloader\lib\samp\events.dll'
	no file 'D:\Grand Theft Auto SA\moonloader\lib\samp.dll'
stack traceback:
	[C]: in function 'require'
	D:\Grand Theft Auto SA\moonloader\SPECTATOR.lua:49: in main chunk

**Comment by RecruitMk** [comment]
download and install this
https://github.com/THE-FYP/SAMP.Lua/releases/download/v2.1.0/samp.zip
